//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankAPI.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductInfo()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int Price { get; set; }
        public Nullable<int> DiscPrice { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string AuxImage { get; set; }
        public int Discount { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public int Views { get; set; }
        public int Bought { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
